name: flashlight
description: This application will turn your smartphone into a super flashlight. You'll find the basic torch functionality with this app.

publish_to: 'none'

version: 1.0.1+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  audioplayers: ^0.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
   - images/
   - assets/